### PR TITLE
Update data.ts

### PR DESCRIPTION
**Pull request by 5h0bh4nk**
Updated tutorial link to practice link

### CODE REVIEW

**Comment by sounishnath003** [comment]
Nice Help!

**Review by sounishnath003 — APPROVED** [review]

**Comment by 5h0bh4nk** [comment]
@sounishnath003 
In graphs section , there are multiple problems for which practice links are available , but tutorial links given  .
Should I update them ?

**Comment by sounishnath003** [comment]
If you find any link for those practicing those questions, You try to add! And also I am trying to build the platform v2.0 with an Authentication part and a real database to sync your progress across the devices you can contribute that also.

** 📌 Checkout and Contribute:** [Verion 2.0](https://github.com/sounishnath003/450-DSA-Tracker/tree/feature/distributed-auth-with-database)

**Comment by 5h0bh4nk** [comment]
The new features seem cool ,
i will start working on it for sure  .

**Pull request merged**
